# Default values for dev-stack.

meilisearch:
  enabled: true
  image: getmeili/meilisearch:latest
  replicas: 1
  service:
    type: LoadBalancer
    port: 7700
  secretName: meilisearch-secret
  extractKeys: true
  devMode: true
  env:
    MEILI_ENV: "development"

ollama:
  enabled: true
  image: ollama/ollama:latest
  replicas: 1
  service:
    type: LoadBalancer
    port: 11435