# Default values for dev-stack.

meilisearch:
  enabled: true
  image: getmeili/meilisearch:latest
  replicas: 1
  service:
    type: NodePort
    port: 7700
  secretName: meilisearch-secret
  extractKeys: true
  devMode: true
  env:
    MEILI_ENV: "development"
    MEILI_MASTER_KEY: "myMasterKey123"  # Only for development

ollama:
  enabled: true
  image: ollama/ollama:latest
  replicas: 1
  service:
    type: NodePort
    port: 11434  # Make sure this is the only port defined
  modelInit:
    enabled: true
    modelName: llama3.2
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "8Gi"
        cpu: "4"