[package]
name = "MazMailChatBot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
ollama-rs = "0.2.4"
hyper = "0.14"
hyper-rustls = "0.23"
google-gmail1 = "3.1.0+20200715"
env_logger = "0.11.6"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }  # use an appropriate version
oauth2 = "4.4"
serde_json = "1.0.138"

