apiVersion: batch/v1
kind: Job
metadata:
  name: meilisearch-extract-keys
spec:
  template:
    spec:
      serviceAccountName: meilisearch-job-account
      containers:
        - name: extract-keys
          # Use an image that already has jq installed
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Installing curl and jq..."
              apk add --no-cache curl jq
              
              echo "Waiting for MeiliSearch to be ready..."
              until curl -s -o /dev/null http://meilisearch:7700/health; do 
                sleep 2
              done
              
              echo "Extracting API keys..."
              API_KEYS=$(curl -s -H "Authorization: Bearer $MEILI_MASTER_KEY" http://meilisearch:7700/keys)
              echo "Raw API keys data: $API_KEYS"
              
              SEARCH_KEY=$(echo "$API_KEYS" | jq -r '.results[] | select(.name=="Default Search API Key") | .key')
              ADMIN_KEY=$(echo "$API_KEYS" | jq -r '.results[] | select(.name=="Default Admin API Key") | .key')
              
              echo "Extracted keys - SEARCH_KEY: $SEARCH_KEY, ADMIN_KEY: $ADMIN_KEY"
              
              if [ -z "$SEARCH_KEY" ] || [ -z "$ADMIN_KEY" ]; then
                echo "Failed to extract API keys. Exiting."
                exit 1
              fi

              # Create Kubernetes secret with the keys
              cat << EOF > /tmp/secret.yaml
              apiVersion: v1
              kind: Secret
              metadata:
                name: meilisearch-api-keys
              type: Opaque
              stringData:
                MEILI_SEARCH_KEY: $SEARCH_KEY
                MEILI_ADMIN_KEY: $ADMIN_KEY
              EOF
              
              echo "Applying the secret..."
              kubectl apply -f /tmp/secret.yaml
              
              echo "API keys successfully stored in Kubernetes secret"
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch-secret
                  key: MEILI_MASTER_KEY
      restartPolicy: Never
  backoffLimit: 3