apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: {{ .Values.meilisearch.replicas }}
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: "{{ .Values.meilisearch.image }}"
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_ENV
              value: "{{ .Values.meilisearch.env.MEILI_ENV }}"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.meilisearch.secretName }}
                  key: MEILI_MASTER_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
spec:
  selector:
    app: meilisearch
  type: {{ .Values.meilisearch.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.meilisearch.service.port }}
      targetPort: 7700