apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-secret
type: Opaque
stringData:
  # Use a fixed master key for development to make it predictable
  MEILI_MASTER_KEY: "masterKey123ForDevOnly"