apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-model-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: model-initializer
          image: curlimages/curl:latest  # Using a simple curl image
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Wait for the Ollama server to be ready
              echo "Waiting for Ollama server to be ready..."
              
              # Try both service endpoints
              OLLAMA_ENDPOINT="http://ollama:{{ .Values.ollama.service.port }}"
              
              MAX_ATTEMPTS=60
              ATTEMPT=0
              
              while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
                ATTEMPT=$((ATTEMPT+1))
                echo "Attempt $ATTEMPT/$MAX_ATTEMPTS: Checking Ollama API..."
              
                if curl -s "$OLLAMA_ENDPOINT/api/tags" > /dev/null 2>&1; then
                  echo "Successfully connected to Ollama server!"
                  break
                fi
              
                echo "Ollama server not ready yet, waiting..."
                sleep 10
              done
              
              if [ $ATTEMPT -ge $MAX_ATTEMPTS ]; then
                echo "Failed to connect to Ollama server after $MAX_ATTEMPTS attempts."
                exit 1
              fi
              
              # Pull the llama3 model using the Ollama API
              echo "Ollama server is up! Pulling llama3 model..."
              
              curl -X POST "$OLLAMA_ENDPOINT/api/pull" \
                -H "Content-Type: application/json" \
                -d '{"name":"{{ .Values.ollama.modelInit.modelName }}"}' \
                --no-buffer
              
              echo "Model pull request sent successfully!"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"